[package]
name = "rtipc-zbus"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "5.13.1"
rtipc = { git = "https://github.com/mausys/rtipc-rust.git", branch = "main" }
zvariant = "5.9.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.200", features = ["derive"] }
